version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KFAKA_HEAP_OPTS: -Xmx64m
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: -Xmx192m
  postgres:
    build: ./postgresql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: bn_local
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data
  zipkin:
    image: openzipkin/zipkin:2.21
    ports:
      - 9411:9411
    environment:
      JAVA_OPTS: -Xmx128m

  cdc-service:
    image: eventuateio/eventuate-cdc-service:0.6.1.RELEASE
    ports:
      - 8099:8080
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181

      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: bn_auth_server

      EVENTUATE_CDC_READER_READER1_TYPE: postgres-wal
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:postgresql://postgres/bn_local
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: postgres
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: p0stgr@s
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/common

  bn-config-server:
    build: ./bn-config-server
    ports:
      - 8888:8888
    depends_on:
      - zipkin
    environment:
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/

  bn-auth-server:
    build: ./proto-authentication-service
    ports:
      - 8081:8080
    depends_on:
      - cdc-service
      - zipkin
      - bn-config-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/bn_local
      SPRING_DATASOURCE_USERNAME: bn_auth_server_user
      SPRING_DATASOURCE_PASSWORD: bn_auth_server_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENUTATE_DATABASE_SCHEMA: bn_auth_server
      JAVA_OPTS: -Xmx192m
      SPRING_SLEUTH_ENABLED: "true"
      SPRING_SLEUTH_SAMPLER_PROBABILITY: 1
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
