version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:5.5.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgresql:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=proto_local

  zipkin:
    image: openzipkin/zipkin:2.21
    ports:
      - 9411:9411
    environment:
      JAVA_OPTS: -Xmx128m


  proto-authentication-service:
    build: ./proto-authentication-service
    ports:
      - 8081:8080
    depends_on:
      - postgresql
      - zipkin
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/proto_local
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: p0stgr@s
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      JAVA_OPTS: -Xmx192m
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411/
